// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Suggests customizations for a user's order based on popular choices and dietary restrictions.
 *
 * @param {SuggestOrderCustomizationsInput} input - The input to the flow, including the user's order and dietary restrictions.
 * @returns {Promise<SuggestOrderCustomizationsOutput>} - A promise that resolves to the suggested customizations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestOrderCustomizationsInputSchema = z.object({
  order: z.string().describe('The user\'s current order.'),
  dietaryRestrictions: z.string().describe('The user\'s dietary restrictions, if any.'),
});
export type SuggestOrderCustomizationsInput = z.infer<typeof SuggestOrderCustomizationsInputSchema>;

const SuggestOrderCustomizationsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of suggested customizations for the order.'),
});
export type SuggestOrderCustomizationsOutput = z.infer<typeof SuggestOrderCustomizationsOutputSchema>;

export async function suggestOrderCustomizations(input: SuggestOrderCustomizationsInput): Promise<SuggestOrderCustomizationsOutput> {
  return suggestOrderCustomizationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestOrderCustomizationsPrompt',
  input: {schema: SuggestOrderCustomizationsInputSchema},
  output: {schema: SuggestOrderCustomizationsOutputSchema},
  prompt: `You are a helpful assistant that suggests customizations for a user's order at The Spice Meal restaurant.

  The user's current order is: {{{order}}}
  The user's dietary restrictions are: {{{dietaryRestrictions}}}

  Suggest customizations based on popular choices and the user's dietary restrictions. Be concise.
  Return an array of suggested customizations.
  `,
});

const suggestOrderCustomizationsFlow = ai.defineFlow(
  {
    name: 'suggestOrderCustomizationsFlow',
    inputSchema: SuggestOrderCustomizationsInputSchema,
    outputSchema: SuggestOrderCustomizationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
