import type { Offer } from './types';

export const offers: Offer[] = [
  {
    id: 'offer-1',
    name: 'Biryani Combo',
    description: 'A delicious Hyderabadi Chicken Biryani served with a refreshing Mango Lassi.',
    price: 500,
    originalPrice: 550,
    restaurantIds: ['restaurant-1', 'restaurant-3'],
    itemIds: ['main-6', 'beverage-1'],
    imageId: 'biryani-combo',
  },
  {
    id: 'offer-2',
    name: 'Vegetarian Feast',
    description: 'A wholesome meal of Palak Paneer and Butter Naan.',
    price: 320,
    originalPrice: 350,
    restaurantIds: ['restaurant-1', 'restaurant-3'],
    itemIds: ['main-2', 'main-5'],
    imageId: 'vegetarian-feast',
  },
  {
    id: 'offer-3',
    name: 'Spicy Chicken Deal',
    description: 'The classic Butter Chicken paired with a soft Butter Naan.',
    price: 300,
    originalPrice: 330,
    restaurantIds: ['restaurant-2'],
    itemIds: ['main-1', 'main-5'],
    imageId: 'chicken-deal',
  },
  {
    id: 'offer-4',
    name: 'Pan Pizza & Pepsi',
    description: 'A Signature Pan Supreme Pizza with a refreshing Pepsi.',
    price: 480,
    originalPrice: 510,
    restaurantIds: ['restaurant-5'],
    itemIds: ['pizza-1', 'beverage-4'],
    imageId: 'pizza-coke-combo',
  },
  {
    id: 'offer-5',
    name: 'Farmhouse & Coke',
    description: 'A Farmhouse Pizza paired with a classic Coca-Cola.',
    price: 410,
    originalPrice: 440,
    restaurantIds: ['restaurant-6'],
    itemIds: ['pizza-3', 'beverage-5'],
    imageId: 'dominos-delight',
  },
  {
    id: 'offer-6',
    name: 'Biryani & Thums Up Combo',
    description: 'A classic Hyderabadi Chicken Biryani served with a refreshing Thums Up.',
    price: 470,
    originalPrice: 500,
    restaurantIds: ['restaurant-3'],
    itemIds: ['main-6', 'beverage-3'],
    imageId: 'biryani-thums-up-combo',
  },
];
